### ISSUE TITLE
Google drive link for validation dataset is wrong

### ISSUE THREAD

**Issue by AterLuna** [jacquelinelala/GFN#10]
In 'Test on LR-GOPRO Validation' session, there's a download link for validation dataset from google drive, but the link is same to the download link for the original GOPRO_Large dataset(file size 8.9GB).
Please fix the link for appropriate file, same to the download link of PanBaidu(file size 2.4GB).

**Comment by jacquelinelala** [comment]
2.4GB is the size of Validation. Please retry the google drive now.
