### ISSUE TITLE
AttributeError: 'Conv2D' object has no attribute 'padding_mode'

### ISSUE THREAD

**Issue by AterLuna** [jacquelinelala/GFN#11]
Environment:
Ubuntu 16.04.6
Python 3.6.7
PyTorch 1.1
CUDA 10.0

I've tried test_GFN_4x.py with your validation set(LR-GOPRO), but it shows
"AttributeError: 'Conv2D' object has no attribute 'padding_mode'"

How can I fix this problem?

**Comment by AterLuna** [comment]
Downgraded PyTorch to 0.4.0

**Comment by 5tr1k3r** [comment]
I had a similar issue and downgrading to PyTorch 1.0.1 helped.

**Comment by thoward27** [comment]
Are there any suggestions for someone who may not want to downgrade?

**Comment by rafaelvalle** [comment]
Iterate over the layers that require the attribute and set them.
