### ISSUE TITLE
Could you please provide the link of BaiduPan for GOPRO_Large dataset?

### ISSUE THREAD

**Issue by musicrainie** [jacquelinelala/GFN#14]
As titled.

**Comment by shinianzhihou** [comment]
Hi，我正在使用百度网盘，给大家分享"GOPRO_Large.zip"，快来看看吧~https://pan.baidu.com/s/1kljRGNHGXcRmCPbPtU2NWg



maybe this one ？

**Comment by shinianzhihou** [comment]
https://pan.baidu.com/s/1kljRGNHGXcRmCPbPtU2NWg

IT IS 2.39G

there is another one(9.*G) but it is so large that it cannot be stored in baidupan

**Comment by musicrainie** [comment]
https://pan.baidu.com/s/1yVkMQ3ynDvcgMCKRvY_YBQ 
4zhq

**Comment by musicrainie** [comment]
Let me know if the above one is invalid.
