### ISSUE TITLE
Training model problem

### ISSUE THREAD

**Issue by sun52525252** [jacquelinelala/GFN#2]
I'm trying to train GFN model by myself. 
Can you provide the traning code and dataset or is there other way to generate the dataset from GoPro dataset by myself?
THX

**Comment by zhLawliet** [comment]
@sun52525252 have you find the gopro_val_generator.m?

**Comment by jacquelinelala** [comment]
The new version is released. Please update the repository and follow the newest README.

**Comment by jacquelinelala** [comment]
The new version is updated. Please follow the newest version.
Thanks a lot.
