### ISSUE TITLE
question about training details --how to train GFN to reach the PSNR 27.74+ on LR-GOPRO 4× 

### ISSUE THREAD

**Issue by LIUHUACHENG** [jacquelinelala/GFN#24]
hello ,Dear author ,Xinyi Zhang:
I meet some problems during training the GFN model.    
I git clone the code and use the README methods to generate training and testing data,use the Default configuration parameters of the model.After complete three stages training to get the stage3-55epoch model,use the completed model to test on testsets,only get about 24 PSNR on on LR-GOPRO 4. But I use the provided pre-training model to test on testset,got 27.81 PSNR,are there some training details or tricks need to add ,if possible ,can you provide more training details?

**Comment by jacquelinelala** [comment]
Hi, you may check the intermediate results of the first two steps. It may occur gradient explosion. By the way, there is no trick in our method. The released model is trained by the released code.

**Comment by LIUHUACHENG** [comment]
Ok, thank your reply,I try it again.

**Comment by cyyycc** [comment]
> Ok, thank your reply,I try it again.

I met the same problem , hava you solved this problem?
