### ISSUE TITLE
please help me :can it test without HR folder?

### ISSUE THREAD

**Issue by FrankLinxzx** [jacquelinelala/GFN#25]
please help me :can it test without HR folder?  i want to test without hr pictures,now it dependent on Hr pictures numbers ,please help me how to fix ,thx

**Comment by jacquelinelala** [comment]
Of course. You may need to comment out some codes about the class of
DataValSet in GFN/datasets/dataset_hf5.py and make it not return HR.
Besides, you need to comments out some code in GFN/test_GFN_4x.py(starts
from line 56). In short, you need to comment out some codes related to HR.
