### ISSUE TITLE
Turn a single LR blurred image into into a high-resolution image

### ISSUE THREAD

**Issue by thaboub** [jacquelinelala/GFN#27]
Hi Zhang,
Great work and great results! Thank you very much.
I am wondering if I could turn a single LR blurred image, without having its corresponding ground truth, into a high-resolution image by using the same developed model. In other words, instead of validating the dataset (GOPRO_Large\LR-GOPRO\Validation_4x), I would like to evaluate only a single LR blurred image and get deblurred. What is the syntax that I can use instead of the below one
python test_GFN_4x.py --dataset GOPRO_Large\LR-GOPRO\Validation_4x

Thank you very much
Abdel

**Comment by jacquelinelala** [comment]
This is the same issue. Please refer to #25
