### ISSUE TITLE
Hello there, Can I use the pre-trained models directly on a Blur/Hazy/Rany images for inference? or I need to have a Ground Truth image for each tested image? 

### ISSUE THREAD

**Issue by yaz94** [jacquelinelala/GFN#29]

**Comment by jacquelinelala** [comment]
answered in #25

**Comment by yaz94** [comment]
Thank you for your response. You are much appreciated. I followed threat #25 
However, can you share the lines that need to be commented? Since I spent some time trying to figure out which ones to comment in both files but I am still struggling.

Thanks in advance.
