### ISSUE TITLE
Do SR/Deblurring tasks always require long epoches?

### ISSUE THREAD

**Issue by miaosiSari** [jacquelinelala/GFN#7]
I love your work. I am a freshman who just started my research in super-resolution. I find that at first several epochs(<=5), the PSNR is just ~20.0dB and ssim ~0.58. I am not challenging your work, but could you please tell me does super-resolution tasks always require a lot of epochs?

**Comment by jacquelinelala** [comment]
Not always, the training time is related to the architecture you use. If you use UNet architecture or the single branch architecture, such as SRResNet or RDN, the converge time will be less than ours. You can also use the residual learning strategy to accelerate the speed step further.

As for our work, the two branch are desinged to handle different degradations (one for deblurring and one for SR), so it will need more time to coordinate them to a better fusion. If you want to seep up the training process, you can also add residual learning to our work. Although you can acquire decent result at first several epochs, the final result is not as good as the original one according to our experiment.
