### ISSUE TITLE
There is no "GOPRO_Large" file in Pan Baidu.

### ISSUE THREAD

**Issue by dyfloveslife** [jacquelinelala/GFN#8]

**Comment by jacquelinelala** [comment]
I've checked the link, and it's useful. You may need to download the "Validation dataset" with Pan Baidu's client. I'd like to mind you that the "original GOPRO_Large" dataset you need to download with Google Drive.

**Comment by dyfloveslife** [comment]
Thank you very much, I have downloaded the test dataset via Pan Baidu and imported the training model `GFN_epoch_55.pkl` .But when I run:
`python test_GFN_x4.py --dataset my_downloads_directory/GOPRO_Large/Validation_4x `
It made a mistake:
`RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:51`

Here are some information about my computer：
cuda version is 8.0
cuDNN version is 5.1
CUDADevice with properties:
Name: 'GeForce GT 755M'

                     Index: 1
         ComputeCapability: '3.0'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 2.1475e+09
           AvailableMemory: 1.7294e+09
       MultiprocessorCount: 2
              ClockRateKHz: 1019500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

How can I solve it? look forward to your reply！

**Comment by jacquelinelala** [comment]
I guess that if you have only one GPU, you may replace the "test_GFN.py" line37 with os.environ['CUDA_VISIBLE_DEVICES'] = '0' , then try it again. If it doesn't work, there is something wrong with your environment.

**Comment by dyfloveslife** [comment]
![image](https://user-images.githubusercontent.com/22425377/54171492-71c4c100-44b5-11e9-9154-79cc34b8d474.png)

The above is the information of my computer GPU, it really has two GPUs.
Are you sure  to modify https://github.com/jacquelinelala/GFN/blob/master/test_GFN_4x.py#L37 ? 
I still have the same error after I modified it.

In addition, here are some of my other information.
```
In [1]：import torch

In [2]：torch.cuda.current_device()
Out[2]：
D:\python\lib\site-packages\torch\cuda\__init__.py:117: UserWarning:
    Found GPU0 GeForce GT 755M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
0

In [3]：torch.cuda.device(0)
Out[3]：<torch.cuda.device object at 0x0000020D0A992E10>

In [4]：torch.cuda.device_count()
Out[4]：1

In [5]：torch.cuda.get_device_name(0)
Out[5]：'GeForce GT 755M'
```

**Comment by jacquelinelala** [comment]
Your GPU0 is an integrated graphics chip, and it doesn't support CUDA. You can't use it. Pytorch doesn't support the second GPU1, because the version is too old. You need to install a lower version of Pytorch to adapt to old GPU. Maybe it will work out.

**Comment by dyfloveslife** [comment]
https://discuss.pytorch.org/t/what-cuda-compute-capability/27885
It seems that I have to compile the source code and use them.
Your answer did solve some of my problems.
Thank you very mach!
